'use client'
import { useState } from 'react'
import Link from 'next/link'

type EmploymentType = 'regular' | 'contract' | 'executive'

function esaNotice(years: number): number {
  if (years < 1) return 1
  if (years < 3) return 2
  if (years < 4) return 3
  if (years < 5) return 4
  if (years < 6) return 5
  if (years < 7) return 6
  if (years < 8) return 7
  return 8
}

function esaSeverance(years: number, qualifies: boolean): number {
  if (!qualifies) return 0
  return Math.min(Math.round(years), 26)
}

function commonLawMonths(years: number, age: number, empType: EmploymentType, isManager: boolean): { low: number; high: number } {
  // Conservative Bardal approach: additive, not multiplicative
  let months = years  // Base: 1 month per year of service
  
  // Age factor (additive)
  if (age >= 50) {
    months += 4
  } else if (age >= 40) {
    months += 2
  }
  
  // Role factor (additive)
  if (empType === 'executive') {
    months += 6
  } else if (isManager) {
    months += 3
  }
  
  // Calculate range with realistic bounds
  // Low estimate: months minus 25%, high estimate: months plus 40%
  const low = Math.round(Math.max(1, months * 0.75) * 10) / 10
  // Cap high end at 24 months (typical for most cases without exceptional circumstances)
  const high = Math.round(Math.min(24, months * 1.4) * 10) / 10
  
  return { low, high }
}

export default function SeveranceEstimator() {
  const [years, setYears] = useState(5)
  const [salary, setSalary] = useState(85000)
  const [age, setAge] = useState(38)
  const [empType, setEmpType] = useState<EmploymentType>('regular')
  const [isManager, setIsManager] = useState(false)
  const [bigPayroll, setBigPayroll] = useState(true)
  const [copied, setCopied] = useState(false)

  const toolSchema = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Severance Pay Estimator',
    description: 'Estimate severance pay for Ontario employment terminations',
    applicationCategory: 'BusinessApplication',
    url: 'https://hillaryshr.blog/tools/severance-estimator',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'CAD',
    },
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://hillaryshr.blog' },
      { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://hillaryshr.blog/tools' },
      { '@type': 'ListItem', position: 3, name: 'Severance Estimator', item: 'https://hillaryshr.blog/tools/severance-estimator' },
    ],
  }

  const weeklyPay = salary / 52
  const noticWeeks = esaNotice(years)
  const noticePay = noticWeeks * weeklyPay
  const severanceWeeks = esaSeverance(years, bigPayroll)
  const severancePay = severanceWeeks * weeklyPay
  const esaTotal = noticePay + severancePay

  const commonLaw = commonLawMonths(years, age, empType, isManager)
  const commonLawLow = (commonLaw.low / 12) * salary
  const commonLawHigh = (commonLaw.high / 12) * salary

  function copySummary() {
    const text = `ONTARIO SEVERANCE ESTIMATE\n\n${years} years | $${salary.toLocaleString()} | Age ${age}\n\nESA MINIMUM: $${Math.round(esaTotal).toLocaleString()}\nCOMMON LAW RANGE: $${Math.round(commonLawLow).toLocaleString()} – $${Math.round(commonLawHigh).toLocaleString()}\n\nGenerated by Hillary&apos;s HR Blog — Not legal advice`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '48px 32px 80px' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(toolSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      {/* Header */}
      <div style={{ marginBottom: '48px' }}>
        <div style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#aaa', marginBottom: '16px' }}>Free HR Tool • Ontario Only</div>
        <h1 style={{ fontFamily: 'var(--font-newsreader)', fontSize: '48px', fontWeight: 300, color: '#1a1a1a', lineHeight: 1, marginBottom: '16px' }}>Severance Pay Estimator</h1>
        <p style={{ fontSize: '14px', color: '#666', maxWidth: '600px', lineHeight: 1.6 }}>Estimate Ontario ESA minimum severance pay and common law range for termination without cause.</p>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'380px 1fr', gap:40, marginBottom:40 }}>

        {/* INPUTS */}
        <div style={{ display:'flex', flexDirection:'column', gap:20 }}>
          <div>
            <label style={{ display:'block', fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'#aaa', marginBottom:8 }}>Years: <span style={{ fontSize:16, color:'#1a1a1a' }}>{years}</span></label>
            <input type="range" min={0.5} max={30} step={0.5} value={years} onChange={e=>setYears(+e.target.value)} style={{ width:'100%' }} />
          </div>

          <div>
            <label style={{ display:'block', fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'#aaa', marginBottom:8 }}>Salary</label>
            <input type="number" value={salary} onChange={e=>setSalary(+e.target.value)} min={0} step={1000}
              style={{ width:'100%', padding:'10px 12px', border:'1.5px solid #ddd', borderRadius:6, fontFamily:'var(--font-roboto)', fontSize:13, outline:'none', color:'#111111', backgroundColor:'#ffffff' }} />
          </div>

          <div>
            <label style={{ display:'block', fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'#aaa', marginBottom:8 }}>Age: <span style={{ fontSize:16, color:'#1a1a1a' }}>{age}</span></label>
            <input type="range" min={18} max={70} step={1} value={age} onChange={e=>setAge(+e.target.value)} style={{ width:'100%' }} />
          </div>

          <div>
            <label style={{ display:'block', fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'#aaa', marginBottom:8 }}>Role Type</label>
            <div style={{ display:'flex', flexDirection:'column', gap:6 }}>
              {(['regular','contract','executive'] as const).map(v => (
                <button key={v} onClick={()=>setEmpType(v)}
                  style={{ padding:'10px 12px', borderRadius:6, fontSize:12, fontWeight:500, cursor:'pointer', textAlign:'left', border:'1.5px solid', borderColor: empType===v ? '#1a1a1a' : '#ddd', background: empType===v ? '#1a1a1a' : '#fff', color: empType===v ? '#fff' : '#1a1a1a' }}>
                  {v === 'regular' ? 'Regular Employee' : v === 'contract' ? 'Contract' : 'Executive'}
                </button>
              ))}
            </div>
          </div>

          <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
            {[
              { label:'Manager role', val:isManager, set:setIsManager },
              { label:'Payroll ≥ $2.5M', val:bigPayroll, set:setBigPayroll },
            ].map(({ label, val, set }) => (
              <button key={label} onClick={()=>set(!val)}
                style={{ display:'flex', alignItems:'center', gap:10, padding:'10px 12px', background:'#fff', border:`1.5px solid ${val ? '#c0392b' : '#ddd'}`, borderRadius:6, cursor:'pointer' }}>
                <div style={{ width:18, height:18, border:`2px solid ${val ? '#c0392b' : '#ddd'}`, borderRadius:4, background: val ? '#c0392b' : 'transparent', display:'flex', alignItems:'center', justifyContent:'center' }}>
                  {val && <span style={{ color:'#fff', fontWeight:800, fontSize:12 }}>✓</span>}
                </div>
                <span style={{ fontSize:12, fontWeight:500, color:'#1a1a1a' }}>{label}</span>
              </button>
            ))}
          </div>

          <button onClick={copySummary} style={{ padding:'10px 14px', background: copied ? '#27ae60' : '#c0392b', color:'#fff', border:'none', borderRadius:6, cursor:'pointer', fontWeight:600, fontSize:12, marginTop:'auto' }}>{copied ? '✓ Copied' : 'Copy Summary'}</button>
        </div>

        {/* RESULTS */}
        <div>
          <div style={{ marginBottom:24 }}>
            <div style={{ fontFamily:'var(--font-newsreader)', fontSize:18, fontWeight:600, color:'#1a1a1a', marginBottom:16 }}>Severance Estimate</div>

            {/* ESA */}
            <div style={{ background:'#fff', border:'1px solid #e8e6e1', borderRadius:8, padding:20, marginBottom:20 }}>
              <div style={{ fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'#aaa', marginBottom:12 }}>ESA Minimums</div>
              <div style={{ display:'flex', justifyContent:'space-between', paddingBottom:12, borderBottom:'1px solid #e8e6e1', marginBottom:12 }}>
                <div>
                  <div style={{ fontSize:12, color:'#666' }}>Termination Notice</div>
                </div>
                <div style={{ fontFamily:'var(--font-newsreader)', fontSize:16, fontWeight:600, color:'#1a1a1a' }}>${Math.round(noticePay).toLocaleString()}</div>
              </div>
              <div style={{ display:'flex', justifyContent:'space-between', paddingBottom:12, borderBottom:'1px solid #e8e6e1', marginBottom:12 }}>
                <div>
                  <div style={{ fontSize:12, color:'#666' }}>ESA Severance</div>
                </div>
                <div style={{ fontFamily:'var(--font-newsreader)', fontSize:16, fontWeight:600, color:'#1a1a1a' }}>${Math.round(severancePay).toLocaleString()}</div>
              </div>
              <div style={{ display:'flex', justifyContent:'space-between' }}>
                <div style={{ fontWeight:600, color:'#1a1a1a' }}>ESA Total</div>
                <div style={{ fontFamily:'var(--font-newsreader)', fontSize:22, fontWeight:600, color:'#1a1a1a' }}>${Math.round(esaTotal).toLocaleString()}</div>
              </div>
            </div>

            {/* Common Law */}
            <div style={{ background:'#1a1a1a', borderRadius:8, padding:20, color:'#fff' }}>
              <div style={{ fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'rgba(192, 57, 43, 0.9)', marginBottom:4 }}>Common Law Range (Without Limitation Clause)</div>
              <div style={{ fontSize:10, color:'rgba(255,255,255,0.4)', marginBottom:12 }}>Assumes no valid limiting/severance clause in the employment contract</div>
              <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12 }}>
                <div>
                  <div style={{ fontSize:11, color:'rgba(255,255,255,0.5)', marginBottom:4 }}>Low Estimate</div>
                  <div style={{ fontFamily:'var(--font-newsreader)', fontSize:22, fontWeight:600 }}>${Math.round(commonLawLow).toLocaleString()}</div>
                </div>
                <div>
                  <div style={{ fontSize:11, color:'rgba(255,255,255,0.5)', marginBottom:4 }}>High Estimate</div>
                  <div style={{ fontFamily:'var(--font-newsreader)', fontSize:22, fontWeight:600 }}>${Math.round(commonLawHigh).toLocaleString()}</div>
                </div>
              </div>
            </div>
          </div>

          <div style={{ padding:12, background:'#fff3cd', border:'1px solid #f59e0b', borderRadius:6, fontSize:11, color:'#7d5a00', lineHeight:1.6 }}>
            <strong>Important Disclaimer:</strong> This tool provides rough estimates only and should NOT be relied upon for actual employment decisions. Common law severance varies significantly based on:
            <ul style={{ margin:'6px 0 0 18px', paddingLeft:0 }}>
              <li>Job market conditions in the industry and geographic location</li>
              <li>Difficulty finding comparable work (character of employment)</li>
              <li>Negotiating power of the parties</li>
              <li>Specific facts of the termination (cause, circumstances)</li>
              <li>Validity and enforceability of any limitation clause in the contract</li>
              <li>Individual court jurisdiction and presiding judge</li>
            </ul>
            <strong style={{ display:'block', marginTop:6 }}>Always consult a qualified Ontario employment lawyer before structuring a severance offer.</strong>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div style={{ maxWidth:'600px', margin:'0 auto', padding:'24px', background:'#f9f8f6', border:'1px solid #e8e6e1', borderRadius:8, textAlign:'center', fontSize:'12px', color:'#aaa' }}>
        <Link href="/tools" style={{ color:'#c0392b', textDecoration:'none', fontWeight:600 }}>← Back to Tools</Link>
      </div>
    </div>
  )
}
