'use client'
import { useState } from 'react'
import Link from 'next/link'

type Holiday = { name: string; date: string; provinces: string[] }

const HOLIDAYS_2026: Holiday[] = [
  { name: "New Year's Day", date: '2026-01-01', provinces: ['ON','BC','AB','QC','MB','SK','NS','NB','NL','PEI','YT','NT','NU'] },
  { name: "Family Day", date: '2026-02-16', provinces: ['ON','AB','SK','NB'] },
  { name: "Good Friday", date: '2026-04-03', provinces: ['ON','BC','AB','QC','MB','SK','NS','NB','NL','PEI','YT','NT','NU'] },
  { name: "Victoria Day", date: '2026-05-18', provinces: ['ON','BC','AB','MB','SK','NS','NB','PEI','YT','NT','NU'] },
  { name: "Canada Day", date: '2026-07-01', provinces: ['ON','BC','AB','QC','MB','SK','NS','NB','NL','PEI','YT','NT','NU'] },
  { name: "Civic Holiday", date: '2026-08-03', provinces: ['ON','MB','SK','PEI'] },
  { name: "Labour Day", date: '2026-09-07', provinces: ['ON','BC','AB','QC','MB','SK','NS','NB','NL','PEI','YT','NT','NU'] },
  { name: "Thanksgiving", date: '2026-10-12', provinces: ['ON','BC','AB','MB','SK','NS','NB','PEI','YT','NT','NU'] },
  { name: "Remembrance Day", date: '2026-11-11', provinces: ['BC','AB','SK','NB','NL','PEI','YT','NT','NU'] },
  { name: "Christmas Day", date: '2026-12-25', provinces: ['ON','BC','AB','QC','MB','SK','NS','NB','NL','PEI','YT','NT','NU'] },
]

const PROVINCE_NAMES: Record<string, string> = {
  ON:'Ontario', BC:'British Columbia', AB:'Alberta', QC:'Quebec', MB:'Manitoba',
  SK:'Saskatchewan', NS:'Nova Scotia', NB:'New Brunswick', NL:'Newfoundland & Labrador',
  PEI:'Prince Edward Island', YT:'Yukon', NT:'Northwest Territories', NU:'Nunavut',
}

// Province-specific holiday premium rates (multiplier if working on the holiday)
const PROVINCE_PREMIUMS: Record<string, number> = {
  ON: 1.5,  // Ontario: 1.5x regular rate OR regular pay + substitute day
  BC: 2.0,  // BC: 2x regular rate if working
  AB: 1.5,  // Alberta: 1.5x regular rate if working
  QC: 1.5,  // Quebec: 1.5x regular rate if working
  MB: 1.5,  // Manitoba: 1.5x regular rate if working
  SK: 1.5,  // Saskatchewan: 1.5x regular rate if working
  NS: 1.5,  // Nova Scotia: 1.5x regular rate if working
  NB: 1.5,  // New Brunswick: 1.5x regular rate if working
  NL: 1.5,  // Newfoundland & Labrador: 1.5x regular rate if working
  PEI: 1.5, // Prince Edward Island: 1.5x regular rate if working
  YT: 1.5,  // Yukon: 1.5x regular rate if working
  NT: 1.5,  // Northwest Territories: 1.5x regular rate if working
  NU: 1.5,  // Nunavut: 1.5x regular rate if working
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr + 'T12:00:00')
  return d.toLocaleDateString('en-CA', { weekday:'short', month:'short', day:'numeric' })
}

function isWeekend(dateStr: string): boolean {
  const d = new Date(dateStr + 'T12:00:00')
  return d.getDay() === 0 || d.getDay() === 6
}

export default function StatHolidayCalculator() {
  const [province, setProvince] = useState('ON')
  const [hourlySalary, setHourlySalary] = useState(25)
  const [isWorking, setIsWorking] = useState(false)
  const [copied, setCopied] = useState(false)

  const provHolidays = HOLIDAYS_2026.filter(h => h.provinces.includes(province))
  const premium = PROVINCE_PREMIUMS[province] || 1.5
  
  // Calculate pay based on whether working or not
  const statPayPerDay = isWorking 
    ? hourlySalary * 8 * premium
    : hourlySalary * 8

  function copyList() {
    const lines = [
      `STATUTORY HOLIDAYS 2026 — ${PROVINCE_NAMES[province]}`,
      `(${provHolidays.length} holidays)`,
      '',
      ...provHolidays.map(h => `${formatDate(h.date)}: ${h.name}${isWeekend(h.date) ? ' (weekend)' : ''}`),
      '',
      'Generated by Hillary&apos;s HR Blog — Not legal advice'
    ]
    navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const weekendHolidays = provHolidays.filter(h => isWeekend(h.date))

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '48px 32px 80px' }}>
      {/* Header */}
      <div style={{ marginBottom: '48px' }}>
        <div style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#aaa', marginBottom: '16px' }}>Free HR Tool</div>
        <h1 style={{ fontFamily: 'var(--font-newsreader)', fontSize: '48px', fontWeight: 300, color: '#1a1a1a', lineHeight: 1, marginBottom: '16px' }}>Statutory Holiday Pay Calculator</h1>
        <p style={{ fontSize: '14px', color: '#666', maxWidth: '600px', lineHeight: 1.6 }}>Complete list of 2026 Canadian statutory holidays by province and territory. Calculate pay based on whether the employee works or doesn&apos;t work the holiday.</p>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 320px', gap:40, marginBottom:40 }}>

        {/* Holiday list */}
        <div>
          <div style={{ marginBottom:20 }}>
            <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:12, flexWrap:'wrap', gap:12 }}>
              <div>
                <div style={{ fontFamily:'var(--font-newsreader)', fontSize:18, fontWeight:600, color:'#1a1a1a' }}>{PROVINCE_NAMES[province]}</div>
                <div style={{ fontSize:12, color:'#666', marginTop:4 }}>{provHolidays.length} holidays in 2026</div>
              </div>
              <button onClick={copyList} style={{ padding:'8px 14px', background: copied ? '#27ae60' : '#c0392b', color:'#fff', border:'none', borderRadius:6, cursor:'pointer', fontWeight:600, fontSize:12 }}>{copied ? '✓ Copied' : 'Copy List'}</button>
            </div>

            <div style={{ display:'flex', flexWrap:'wrap', gap:6, marginBottom:20 }}>
              {Object.entries(PROVINCE_NAMES).map(([code]) => (
                <button key={code} onClick={()=>setProvince(code)}
                  style={{ padding:'6px 12px', borderRadius:6, fontSize:11, fontWeight:500, cursor:'pointer', border:'1.5px solid', borderColor: province===code ? '#1a1a1a' : '#ddd', background: province===code ? '#1a1a1a' : '#fff', color: province===code ? '#fff' : '#1a1a1a', transition:'all .15s' }}>
                  {code}
                </button>
              ))}
            </div>
          </div>

          <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
            {provHolidays.map(h => {
              const past = new Date(h.date + 'T12:00:00') < new Date()
              const weekend = isWeekend(h.date)
              return (
                <div key={h.date + h.name} style={{ display:'flex', alignItems:'center', gap:12, padding:'12px 16px', background: '#fff', border:'1px solid #e8e6e1', borderRadius:6, opacity: past ? 0.5 : 1 }}>
                  <div style={{ width:40, textAlign:'center', flexShrink:0 }}>
                    <div style={{ fontFamily:'var(--font-newsreader)', fontSize:18, fontWeight:600, color:'#1a1a1a', lineHeight:1 }}>
                      {new Date(h.date + 'T12:00:00').getDate()}
                    </div>
                    <div style={{ fontSize:10, color:'#aaa', textTransform:'uppercase', marginTop:2 }}>
                      {new Date(h.date + 'T12:00:00').toLocaleDateString('en-CA', { month:'short' })}
                    </div>
                  </div>
                  <div style={{ flex:1 }}>
                    <div style={{ fontSize:13, fontWeight:500, color:'#1a1a1a' }}>{h.name}</div>
                  </div>
                  {weekend && <span style={{ fontSize:9, fontWeight:700, padding:'2px 6px', background:'#fff3cd', color:'#7d5a00', borderRadius:3 }}>Weekend</span>}
                </div>
              )
            })}
          </div>

          {weekendHolidays.length > 0 && (
            <div style={{ marginTop:16, padding:12, background:'#fff3cd', border:'1px solid #f59e0b', borderRadius:6, fontSize:11, color:'#7d5a00' }}>
              <strong>Weekend holidays:</strong> {weekendHolidays.map(h=>h.name).join(', ')}. Check your province for substitute day rules.
            </div>
          )}
        </div>

        {/* Pay calculator */}
        <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
          <div style={{ background:'#1a1a1a', borderRadius:8, padding:20, color:'#fff' }}>
            <div style={{ fontSize:11, fontWeight:700, letterSpacing:1, textTransform:'uppercase', color:'rgba(192, 57, 43, 0.9)', marginBottom:10 }}>Holiday Pay Calculator</div>

            <div style={{ marginBottom:12 }}>
              <label style={{ display:'block', fontSize:11, fontWeight:700, color:'rgba(255,255,255,0.5)', letterSpacing:1, textTransform:'uppercase', marginBottom:6 }}>Hourly Rate</label>
              <input type="number" value={hourlySalary} onChange={e=>setHourlySalary(+e.target.value)} min={17}  step={0.5}
                style={{ width:'100%', padding:'8px 10px', border:'1px solid rgba(255,255,255,0.2)', borderRadius:4, background:'rgba(255,255,255,0.05)', color:'#fff', fontFamily:'var(--font-roboto)', fontSize:13, outline:'none' }} />
            </div>

            <div style={{ marginBottom:12 }}>
              <label style={{ display:'block', fontSize:11, fontWeight:700, color:'rgba(255,255,255,0.5)', letterSpacing:1, textTransform:'uppercase', marginBottom:8 }}>Scenario</label>
              <div style={{ display:'flex', gap:8 }}>
                {(['not_working', 'working'] as const).map(v => (
                  <button key={v} onClick={()=>setIsWorking(v === 'working')}
                    style={{ flex:1, padding:'8px 10px', borderRadius:6, fontSize:11, fontWeight:600, cursor:'pointer', border:'1.5px solid', borderColor: (v === 'working') === isWorking ? 'rgba(192, 57, 43, 0.9)' : 'rgba(255,255,255,0.2)', background: (v === 'working') === isWorking ? 'rgba(192, 57, 43, 0.2)' : 'transparent', color: '#fff' }}>
                    {v === 'working' ? 'Working' : 'Not Working'}
                  </button>
                ))}
              </div>
            </div>

            <div style={{ padding:12, background:'rgba(0,0,0,0.3)', borderRadius:4 }}>
              <div style={{ fontSize:10, color:'rgba(255,255,255,0.5)', marginBottom:4 }}>Holiday Pay Per Day (8 hrs)</div>
              <div style={{ fontFamily:'var(--font-newsreader)', fontSize:24, fontWeight:600 }}>
                ${Math.round(statPayPerDay).toLocaleString()}
              </div>
              <div style={{ fontSize:9, color:'rgba(255,255,255,0.3)', marginTop:4 }}>
                {isWorking ? `${premium}x rate if working` : 'Regular rate if not working'}
              </div>
              <div style={{ fontSize:10, color:'rgba(255,255,255,0.4)', marginTop:6 }}>
                {provHolidays.length} holidays/yr ≈ ${(provHolidays.length * Math.round(statPayPerDay)).toLocaleString()}
              </div>
            </div>
          </div>

          <div style={{ padding:12, background:'#f9f8f6', border:'1px solid #e8e6e1', borderRadius:6, fontSize:10, color:'#666', lineHeight:1.5 }}>
            <strong>Note:</strong> Rates shown are statutory minimums. Employers may offer higher rates. Rates vary by province and employment agreement.
          </div>
        </div>
      </div>

      {/* Footer */}
      <div style={{ maxWidth:'600px', margin:'0 auto', padding:'24px', background:'#f9f8f6', border:'1px solid #e8e6e1', borderRadius:8, textAlign:'center', fontSize:'12px', color:'#aaa' }}>
        <Link href="/tools" style={{ color:'#c0392b', textDecoration:'none', fontWeight:600 }}>← Back to Tools</Link>
      </div>
    </div>
  )
}
